archetype.artifact.id=${archetypeArtifactId}
archetype.version=${archetypeVersion}
artifact.id=${artifactId}
artifact.version=${version}
project.build.timestamp=${maven.build.timestamp}
java.version=${java.version}
maven.version=${maven.version}